### ISSUE TITLE
Integrate with orgmode

### ISSUE THREAD

**Issue by arussel** [jxa/pivotal-tracker#16]
Is there a way to integrate with orgmode ? Ideally, I would be able to tag some pivotal issue as orgmode todo and be able to clock in/out of them and see them in my clock table.

**Comment by ryanprior** [comment]
Charles Francis got a start on this 5 years ago, it looks like:
https://github.com/agentcoops/Pivotal-Mode/blob/master/pivotal.el

His code uses the same license as this project, so feel free to experiment with pulling in some of his org integration stuff.

**Comment by arussel** [comment]
thanks, I'll look into it.
