### ISSUE TITLE
Keybindings on README has no direct correspondence to the one provided in the package

### ISSUE THREAD

**Issue by jethrokuan** [jxa/pivotal-tracker#17]
Hey,

I'm not sure if this is the place to ask this anymore, but I've noticed keys like `e` are not binded like they're described in the README.

Is this project still maintained?

**Comment by jasonm23** [comment]
### Projects View

-[ ] <kbd>M-x pivotal</kbd> will display a list of your current projects 
-[ ] <kbd>RET</kbd> or <kbd>.</kbd> will load the current iteration for the given project
-[ ] <kbd>n</kbd> and <kbd>p</kbd> move between lines, like dired mode
-[ ] <kbd>o</kbd> will open the given project in an external web browser

### Current Project View

-[ ] <kbd>t</kbd> toggles expanded view for a story. <kbd>Enter</kbd> also toggles this view
-[ ] <kbd>R</kbd> refreshes the view
-[ ] <kbd>L</kbd> list projects. displays the Projects View
-[ ] <kbd>N</kbd> will load and display the next iteration
-[ ] <kbd>P</kbd> will load and display the previous iteration
-[ ] <kbd>E</kbd> will prompt for a new integer estimate for that story
-[ ] **numeric prefix** + <kbd>E</kbd> will use that number for the estimate
  **example: pressing <kbd>2</kbd> followed by pressing <kbd>E</kbd> will assign a **2 pt** estimate for current story
-[ ] <kbd>C</kbd> will prompt for a new comment
-[ ] <kbd>S</kbd> will prompt for new status
-[ ] <kbd>O</kbd> will prompt for new story owner
-[ ] <kbd>T</kbd> will prompt for a new task
-[ ] <kbd>F</kbd> will mark the task (not the story) under the cursor as finished
-[ ] <kbd>+</kbd> adds a new story
-[ ] <kbd>l</kbd> saves the url of the given story to the kill-ring (copies it)
-[ ] <kbd>o</kbd> will open the given story in an exernal browser
-[ ] <kbd>C-o</kbd> will open the current project in an external browser

**Comment by jasonm23** [comment]
Fixes covered in PR #20
